HelloPerson = "Hello {{.Name}}"

[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."

[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."

[Hello]
description = "Hello"
one = "Hello one."
other = "Hello other."

[InvalidMissing]
description = "Parameter Is Missing, must be exsits"
one = "{{.Name}}がいません。"
other = "{{.Name}}達がいません。"
